name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/unit-tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests inside Airflow container
        run: |
          docker compose up -d postgres redis airflow-init airflow-webserver
          docker compose exec -T airflow-webserver pip install pytest
          docker compose exec -T airflow-webserver python -m pytest -v tests/test_validate_record.py